import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertCircle, Download, FileText, Loader2, Send, Trash2, CheckCircle2 } from "lucide-react";
import { PendingDocument } from "../types";

const getStatusBadge = (status: string | null) => {
  switch (status) {
    case "pending":
      return (
        <Badge className="bg-orange-500/10 text-orange-600 border-orange-200 hover:bg-orange-500/20">
          Pending
        </Badge>
      );
    case "sent":
      return (
        <Badge className="bg-blue-500/10 text-blue-600 border-blue-200 hover:bg-blue-500/20">
          Sent
        </Badge>
      );
    case "invoice_sent":
      return (
        <Badge className="bg-green-500/10 text-green-600 border-green-200 hover:bg-green-500/20">
          <CheckCircle2 className="h-3 w-3 mr-1" />
          Invoice Sent
        </Badge>
      );
    case "invoice_paid":
      return (
        <Badge className="bg-purple-500/10 text-purple-600 border-purple-200 hover:bg-purple-500/20">
          Invoice Paid
        </Badge>
      );
    default:
      return (
        <Badge className="bg-orange-500/10 text-orange-600 border-orange-200 hover:bg-orange-500/20">
          Pending
        </Badge>
      );
  }
};

interface PendingContractsProps {
  pendingDocuments: PendingDocument[];
  loadingPendingDocs: boolean;
  updatingStatus: Map<string, boolean>;
  sendingInvoice: Map<string, boolean>;
  onMarkAsSent: (docId: string) => void;
  onSendInvoiceClick: (doc: PendingDocument) => void;
  onDownload: (doc: PendingDocument) => void;
  onDelete: (docId: string) => void;
  title?: string;
  description?: string;
  badgeLabel?: string;
  emptyMessage?: string;
}

export const PendingContracts = ({
  pendingDocuments,
  loadingPendingDocs,
  updatingStatus,
  sendingInvoice,
  onMarkAsSent,
  onSendInvoiceClick,
  onDownload,
  onDelete,
  title,
  description,
  badgeLabel,
  emptyMessage,
}: PendingContractsProps) => (
  <Card>
    <CardHeader>
      <div className="flex items-center justify-between">
        <div>
          <CardTitle className="flex items-center gap-2">
            <AlertCircle className="h-5 w-5 text-orange-500" />
            {title ?? "Pending Contracts"}
          </CardTitle>
          <p className="text-sm text-muted-foreground mt-1">
            {description ?? "Contracts ready for DocuSign - download and send to clients"}
          </p>
        </div>
        <Badge variant="secondary">
          {badgeLabel ?? `${pendingDocuments.length} contracts`}
        </Badge>
      </div>
    </CardHeader>
    <CardContent>
      {loadingPendingDocs ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      ) : pendingDocuments.length === 0 ? (
        <div className="text-center py-12">
          <FileText className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
          <p className="text-muted-foreground">
            {emptyMessage ?? "No pending contracts. They will appear here when generated by n8n."}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {pendingDocuments.map((doc) => (
            <div
              key={doc.id}
              className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50 transition-colors"
            >
              <div className="flex items-center gap-3 flex-1">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-orange-500/10">
                  <FileText className="h-5 w-5 text-orange-500" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-medium truncate">{doc.document_name}</p>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <span className="font-mono">
                      {doc.clients?.client_id || "Unknown"}
                    </span>
                    <span>•</span>
                    <span>{doc.clients?.client_name || doc.clients?.client_email}</span>
                    <span>•</span>
                    <span>
                      {new Date(doc.uploaded_at).toLocaleDateString("en-US", {
                        month: "short",
                        day: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </span>
                  </div>
                  {doc.description && (
                    <p className="text-sm text-muted-foreground mt-1">
                      {doc.description}
                    </p>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="flex-shrink-0">
                  {getStatusBadge(doc.contract_status)}
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="default"
                    size="sm"
                    onClick={() => onDownload(doc)}
                    disabled={updatingStatus.get(doc.id) || sendingInvoice.get(doc.id)}
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>

                  {(doc.contract_status === "pending" || doc.contract_status === null) && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => onMarkAsSent(doc.id)}
                      disabled={updatingStatus.get(doc.id) || sendingInvoice.get(doc.id)}
                    >
                      {updatingStatus.get(doc.id) ? (
                        <>
                          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                          Updating...
                        </>
                      ) : (
                        <>
                          <Send className="h-4 w-4 mr-2" />
                          Mark as Sent
                        </>
                      )}
                    </Button>
                  )}

                  {doc.contract_status === "sent" && (
                    <Button
                      variant="default"
                      size="sm"
                      className="bg-green-600 hover:bg-green-700"
                      onClick={() => onSendInvoiceClick(doc)}
                      disabled={updatingStatus.get(doc.id) || sendingInvoice.get(doc.id)}
                    >
                      {sendingInvoice.get(doc.id) ? (
                        <>
                          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                          Sending...
                        </>
                      ) : (
                        <>
                          <Send className="h-4 w-4 mr-2" />
                          Send Invoice
                        </>
                      )}
                    </Button>
                  )}

                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => onDelete(doc.id)}
                    disabled={updatingStatus.get(doc.id) || sendingInvoice.get(doc.id)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </CardContent>
  </Card>
);

