import { PendingContracts } from "./PendingContracts";
import type { PendingDocument } from "../types";

interface PendingContractsTabProps {
  pendingContracts: PendingDocument[];
  sentContracts: PendingDocument[];
  invoiceSentContracts: PendingDocument[];
  loadingPendingDocs: boolean;
  updatingStatus: Map<string, boolean>;
  sendingInvoice: Map<string, boolean>;
  onMarkAsSent: (docId: string) => Promise<void>;
  onSendInvoiceClick: (doc: PendingDocument) => void;
  onDownload: (doc: PendingDocument) => Promise<void>;
  onDelete: (docId: string) => Promise<void>;
}

export const PendingContractsTab = ({
  pendingContracts,
  sentContracts,
  invoiceSentContracts,
  loadingPendingDocs,
  updatingStatus,
  sendingInvoice,
  onMarkAsSent,
  onSendInvoiceClick,
  onDownload,
  onDelete,
}: PendingContractsTabProps) => {
  return (
    <div className="space-y-8">
      <PendingContracts
        pendingDocuments={pendingContracts}
        loadingPendingDocs={loadingPendingDocs}
        updatingStatus={updatingStatus}
        sendingInvoice={sendingInvoice}
        onMarkAsSent={onMarkAsSent}
        onSendInvoiceClick={onSendInvoiceClick}
        onDownload={onDownload}
        onDelete={onDelete}
        title="Pending Contracts"
        description="Contracts ready to be sent to clients"
        badgeLabel={`${pendingContracts.length} not sent yet`}
        emptyMessage="No pending contracts. They will appear here when generated by n8n."
      />

      <PendingContracts
        pendingDocuments={sentContracts}
        loadingPendingDocs={loadingPendingDocs}
        updatingStatus={updatingStatus}
        sendingInvoice={sendingInvoice}
        onMarkAsSent={async () => {}}
        onSendInvoiceClick={onSendInvoiceClick}
        onDownload={onDownload}
        onDelete={onDelete}
        title="Sent Contracts"
        description="Contracts that were marked as sent. Click Send Invoice once signed."
        badgeLabel={`${sentContracts.length} sent`}
        emptyMessage="No sent contracts waiting for invoicing."
      />

      <PendingContracts
        pendingDocuments={invoiceSentContracts}
        loadingPendingDocs={loadingPendingDocs}
        updatingStatus={updatingStatus}
        sendingInvoice={sendingInvoice}
        onMarkAsSent={async () => {}}
        onSendInvoiceClick={onSendInvoiceClick}
        onDownload={onDownload}
        onDelete={onDelete}
        title="Awaiting Payment"
        description="Invoices have been sent. These will disappear automatically when marked paid."
        badgeLabel={`${invoiceSentContracts.length} awaiting payment`}
        emptyMessage="No invoices awaiting payment."
      />
    </div>
  );
};

